name: NeverLag
main: cn.jiongjionger.neverlag.NeverLag
version: 1.7.10-1.3.1
authors: [jiongjionger,Himmelt]
depend: [ProtocolLib]
commands:
    neverlag:
        description: NeverLag
        usage: /neverlag <something>
